@extends('layouts.app') @section('title', 'Financeiro') @section('content')
<div class="row mb-4"> <div class="col-12 d-flex justify-content-between align-items-center"> <h2 class="fw-bold text-primary mb-0"><i class="fa-solid fa-dollar-sign me-2"></i> Controle Financeiro</h2> <a href="{{ route('finance.create') }}" class="btn btn-primary fw-bold px-4 rounded-pill shadow-sm"> <i class="fa-solid fa-plus me-1"></i> Novo Lançamento </a> </div>
</div> <!-- Resumo Cards -->
<div class="row mb-4"> <div class="col-md-4 mb-3 mb-md-0"> <div class="card shadow-sm border-0 border-start border-success border-5 rounded-4"> <div class="card-body p-4"> <div class="text-muted fw-semibold mb-1">Total de Entradas</div> <h3 class="fw-bold text-success mb-0">R$ {{ number_format($summary['entradas'], 2, ',', '.') }}</h3> </div> </div> </div> <div class="col-md-4 mb-3 mb-md-0"> <div class="card shadow-sm border-0 border-start border-danger border-5 rounded-4"> <div class="card-body p-4"> <div class="text-muted fw-semibold mb-1">Total de Saídas</div> <h3 class="fw-bold text-danger mb-0">R$ {{ number_format($summary['saidas'], 2, ',', '.') }}</h3> </div> </div> </div> <div class="col-md-4"> <div class="card shadow-sm border-0 border-start border-{{ $summary['saldo'] >= 0 ? 'primary' : 'warning' }} border-5 rounded-4"> <div class="card-body p-4"> <div class="text-muted fw-semibold mb-1">Saldo Atual</div> <h3 class="fw-bold text-{{ $summary['saldo'] >= 0 ? 'primary' : 'warning' }} mb-0">R$ {{ number_format($summary['saldo'], 2, ',', '.') }}</h3> </div> </div> </div>
</div> <div class="card shadow-sm border-0 rounded-4"> <div class="card-body p-4"> @if(session('success')) <div class="alert alert-success alert-dismissible fade show" role="alert"> {{ session('success') }} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> </div> @endif <div class="table-responsive"> <table class="table table-hover align-middle" id="financeTable"> <thead class="table-light"> <tr> <th>Data</th> <th>Descrição</th> <th>Tipo</th> <th>Forma de Pagto</th> <th>Valor (R$)</th> <th class="text-end">Ações</th> </tr> </thead> <tbody> @foreach($transactions as $trans) <tr> <td>{{ $trans->data->format('d/m/Y') }}</td> <td class="fw-semibold">{{ $trans->descricao }}</td> <td> @if($trans->tipo == 'entrada') <span class="badge bg-success"><i class="fa-solid fa-arrow-up me-1"></i> Entrada</span> @else <span class="badge bg-danger"><i class="fa-solid fa-arrow-down me-1"></i> Saída</span> @endif </td> <td>{{ $trans->forma_pagamento ?? '-' }}</td> <td class="fw-bold {{ $trans->tipo == 'entrada' ? 'text-success' : 'text-danger' }}"> {{ $trans->tipo == 'entrada' ? '+' : '-' }} R$ {{ number_format($trans->valor, 2, ',', '.') }} </td> <td class="text-end"> @can('admin') <form action="{{ route('finance.destroy', $trans->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Excluir lançamento? Isso alterará o seu saldo atual. Tem certeza?');"> @csrf @method('DELETE') <button type="submit" class="btn btn-sm btn-outline-danger rounded-3"> <i class="fa-solid fa-trash"></i> </button> </form> @endcan </td> </tr> @endforeach </tbody> </table> </div> </div>
</div> <script> document.addEventListener('DOMContentLoaded', function() { if (typeof jQuery !== 'undefined' && $.fn.DataTable) { $('#financeTable').DataTable({ language: { url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/pt-BR.json' }, ordering: true, order: [], // Respeita a ordenação exata do servidor no carregamento inicial info: false }); } });
</script>
@endsection

